infra: pipelines updated

diff --git a/.github/workflows/deploy-docker.yml b/.github/workflows/deploy-docker.yml
--- a/.github/workflows/deploy-docker.yml
+++ b/.github/workflows/deploy-docker.yml
@@ -9,7 +9,48 @@ on:
   workflow_dispatch:
 
 jobs:
+  test:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Set up Go
+        uses: actions/setup-go@v5
+        with:
+          go-version-file: 'back/api/go.mod'
+
+      - name: Run tests
+        run: |
+          cd back/api
+          go test ./...
+
+  setup-docker:
+    needs: test
+    runs-on: ubuntu-latest
+    steps:
+      - name: Install Docker on server
+        uses: appleboy/ssh-action@v1.0.3
+        with:
+          host: ${{ secrets.ORACLE_HOST }}
+          username: ${{ secrets.ORACLE_USERNAME }}
+          key: ${{ secrets.ORACLE_PRIVATE_KEY }}
+          script: |
+            if ! command -v docker &> /dev/null; then
+              echo "Docker not found. Installing Docker..."
+              sudo dnf update -y
+              sudo dnf install -y dnf-utils zip unzip
+              sudo dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
+              sudo dnf install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
+              sudo systemctl enable docker --now
+              sudo usermod -aG docker $USER
+              echo "Docker installed successfully."
+            else
+              echo "Docker is already installed."
+            fi
+
   deploy:
+    needs: setup-docker
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
@@ -50,19 +91,7 @@ jobs:
           username: ${{ secrets.ORACLE_USERNAME }}
           key: ${{ secrets.ORACLE_PRIVATE_KEY }}
           script: |
-            # 1. Install Docker and Docker Compose if not present
-            if ! command -v docker &> /dev/null; then
-              echo "Docker not found. Installing Docker..."
-              sudo dnf update -y
-              sudo dnf install -y dnf-utils zip unzip
-              sudo dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
-              sudo dnf install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
-              sudo systemctl enable docker --now
-              sudo usermod -aG docker $USER
-              echo "Docker installed successfully."
-            fi
-            
-            # 2. Deploy using Docker Compose
+            # Deploy using Docker Compose
             cd ~/inkomi/back/api
             sudo docker compose down
             sudo docker compose build --no-cache
